### ISSUE TITLE
number of frames decoded does not match

### ISSUE THREAD

**Issue by psteinb** [strukturag/libde265#123]
Hi,
I've been playing around with h265 encoding/decoding for a scientific "compression" library. I started off using the ffmpeg based libav* API and succeeded in modifying the decoding_encoding.c example so I could produce a h265 file. However, I have a hard time decoding the h265 bitstream. Here is the code for reference:
https://gist.github.com/psteinb/bf12348d799108f390f5
I already posted to the libav-users mailing list, but with no reply yet
https://lists.ffmpeg.org/pipermail/libav-user/2015-August/008385.html

If I use dec265 to decode the stream, the tool reports 22 frames instead of 25 which I'd expect. Any idea, what is going on?
Best -

**Comment by czkang** [comment]
Like you, I am study the libav* API and I posted to the mailing list but no reply. 

As the beginning of  my study,  I am sorry that I can’t help you.  

 

发件人: Peter Steinbach [mailto:notifications@github.com] 
发送时间: 2015年8月13日星期四 20:25
收件人: strukturag/libde265
主题: [libde265] number of frames decoded does not match (#123)

 

Hi,
I've been playing around with h265 encoding/decoding for a scientific "compression" library. I started off using the ffmpeg based libav* API and succeeded in modifying the decoding_encoding.c example so I could produce a h265 file. However, I have a hard time decoding the h265 bitstream. Here is the code for reference:
https://gist.github.com/psteinb/bf12348d799108f390f5
I already posted to the libav-users mailing list, but with no reply yet
https://lists.ffmpeg.org/pipermail/libav-user/2015-August/008385.html

If I use dec265 to decode the stream, the tool reports 22 frames instead of 25 which I'd expect. Any idea, what is going on?
Best -

**Comment by psteinb** [comment]
that is comforting ;)

**Comment by psteinb** [comment]
https://github.com/psteinb/libav-h26x-sandbox
