### ISSUE TITLE
error when running encoder

### ISSUE THREAD

**Issue by ggeor** [strukturag/libde265#125]
Hi,

i successfully compiled the encoder code, but when i run it i got an error:

lt-enc265: image.cc:241: de265_error de265_image::alloc_image(int, int, de265_chroma, const seq_parameter_set*, bool, decoder_context*, encoder_context*, de265_
PTS, void*, bool): Assertion `sps' failed.
Aborted (core dumped)

comman used : ./enc265  -i akiyo_cif.yuv -w 352 -h 288 -o out.bin --sop-structure intra
the platform is ARM A15 Cortex and the OS ubuntu 13.10, however the platform is unlikely to be the reason?

BR,
George

**Comment by czkang** [comment]
I am sorry I can't help you because I am a starter of studying libde265.来自我的华为手机-------- 原始邮件 --------主题：[libde265] error when running encoder (#125)发件人：ggeor 收件人：strukturag/libde265 抄送：Hi,

i successfully compiled the encoder code, but when i run it i got an error:

lt-enc265: image.cc:241: de265_error de265_image::alloc_image(int, int, de265_chroma, const seq_parameter_set, bool, decoder_context, encoder_context, de265_
PTS, void, bool): Assertion `sps' failed.
Aborted (core dumped)

comman used : ./enc265  -i akiyo_cif.yuv -w 352 -h 288 -o out.bin --sop-structure intra
the platform is ARM A15 Cortex and the OS ubuntu 13.10, however the platform is unlikely to be the reason?

BR,
George

**Comment by farindk** [comment]
The encoder is under development. It is not stable for now.
Latest source is in the 'encoder' branch. This should currently be working, but it is not production ready code.

**Comment by d-chand** [comment]
Hi 

i successfully compiled the encoder code, but when i run it i got an error.
command used :   ./enc265 -i akiyo_cif.yuv -w 640 -h 360 -o out.bin

Error :

./enc265 -i ../../akiyo_qcif.yuv -v -v -v  -w 640 -h 360 -o out.265
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
additional block allocated in memory pool
enc265: /home/shashi/Digendra/LIBDE265/libde265/libde265/encoder/encoder-syntax.cc:1484: void encode_coding_unit(encoder_context*, CABAC_encoder*, const enc_cb*, int, int, int, bool): Assertion `cb->split_cu_flag == 0' failed.

    
Let me know if there is something wrong in using encoder.

Thanks
Digendra Chand
