### ISSUE TITLE
API tutorial still uses deprecated(?) de265_release_picture

### ISSUE THREAD

**Issue by Tee0125** [strukturag/libde265#153]
de265_release_picture is not exist in current code, and it may be replaced to de265_release_picture but api tutorial seems to be out-dated.

https://github.com/strukturag/libde265/wiki/Decoder-API-Tutorial

**Comment by farindk** [comment]
It is actually the opposite: de265_release_picture will be needed in the new revision of the API (in the old API, the images were implicitly freed, which turned out to complicate things).
The code in the master branch is still the old API. The new API is in branch "frame_parallel". Please use this for new developments. The tutorial page already refers to this new API.
