### ISSUE TITLE
random failure

### ISSUE THREAD

**Issue by fjhub** [strukturag/libde265#155]
I used dec265 from the master branch as a model for creating the ability to decode from within a library.  I created a test harness that would allow me to perform multiple decode operations at the same time as separate asynchronous tasks.

Things work as expected if I use a single task.  However, I experienced random failures when decoding if I use 2+ asynchronous tasks.  Sometimes things completes as expected and sometimes not.  In going through the issues I came across a few comments where the suggestion was made to use the frame-parallel branch.

So I pulled it down and built things and my application seemed to be worse off as the action 'de265_action_get_image' never came about.  I took one of the compressed data files and ran it through dec265 and I got no decoded image.  The same image works fine with the master branch dec265 application.

Any thoughts?

**Comment by farindk** [comment]
I have no obvious idea what could be the reason for this. There are no
global variables in the decoder and as long as you use separate decoder
contexts, you should be fine. However, I did not try running multiple
decoders in parallel myself yet.

If you have a video that does not decode with 'dec265', you could send it
to me to have a closer look.
I can provide you with a link where to upload the video, if you want.
Please send me an email (farin@struktur.de) so that I can reply back with
an upload link.


2017-10-22 16:41 GMT+02:00 fjhub <notifications@github.com>:

**Comment by fjhub** [comment]
My first thought was that there may be global variables and in my quick analysis I came across the static init counter in the library source file de265.cc.  It seemed that If I didn't call the end function dec265_free_decoder() than things worked more consistently...of course then the memory leak(s) became obvious.

Thanks for taking a look...

**Comment by farindk** [comment]
Thanks for sending the sample file. Bug in VUI parameter decoding is corrected now.
