### ISSUE TITLE
Block until an image was decoded.

### ISSUE THREAD

**Issue by darfire** [strukturag/libde265#274]
Hi,
First of all , great job on the project.

I'd like to know if there's a way to have de265_decode wait until an image is available, without busy-waiting on it. I have read the entire file and called de265_push_end_of_frame after pushing the data yet the first few calls on de265_decode return error = DE265_OK and more = 1 and when getting the next image I get NULL. I understand that this is related to the threaded architecture, I'd just like to know if there's a way to block until the next image is ready, either directly or through another mechanism (callback, polling, etc.).

Thanks.

**Comment by farindk** [comment]
`de265_decode` is not really polling. Every time you call `de265_decode`, some real work is done to decode an image and it blocks until the decoding is finished. Parallel decoding threads are only executed during de265_decode. Because of the frame reordering, it may be that not every time an image is returned when you call de265_decode. On the other hand, it may sometimes return images without having to decode anything.

You are probably doing everything correctly. Simply run `de265_decode` in the loop. This is not busy polling.

PS: make sure to also call de265_flush_data() at the end of the stream.

**Comment by darfire** [comment]
Thanks for the reply, interesting design choice, but it makes sense.
