### ISSUE TITLE
Stack-buffer-overflow READ 4 · void apply_sao_internal<unsigned short> 

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libde265#326]
The https://github.com/ImageMagick project is using the oss-fuzz tooling of google and with the attached file there is a stack-buffer-overflow in `apply_sao_internal`:

https://github.com/strukturag/libde265/blob/e587ef6e8000662b91c35ccb866c2374d3a40e27/libde265/sao.cc#L270

[test.zip](https://github.com/strukturag/libde265/files/9034992/test.zip)

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47804

**Comment by farindk** [comment]
I was not able to reproduce this issue. I tried with old versions back to v1.0.8 and on old Ubuntu 16.04.
h265 stream extracted from test.heic: [issue326.zip](https://github.com/strukturag/libde265/files/10518379/issue326.zip)

Please check whether the issue is still present as I have fixed several issues that appear related.

**Comment by dlemstra** [comment]
Seeing this on the oss-fuzz website: `ClusterFuzz testcase 5208730922254336 is closed as invalid, so closing issue.`. So I will close this.
