### ISSUE TITLE
Broken pc file in autotools build

### ISSUE THREAD

**Issue by antonio-rojas** [strukturag/libde265#387]
Commit 388b61459c2abe2b949114ab54e83fb4dbfa8ba0 produces a broken pc file in the autotools build, the variables are cmake specific and are not properly replaced.

**Comment by LeSuisse** [comment]
We encountered the same issue while updating libde265 in nixpkgs (https://github.com/NixOS/nixpkgs/pull/213046). The pc file is broken when building with the autotools or with cmake. We ended up reverting 388b61459c2abe2b949114ab54e83fb4dbfa8ba0 for the time being and continue to use the autotools build.

**Comment by kmilos** [comment]
Furthermore, this is should be handled in a much better way for CMake anyway in order to support both relative and absolute paths in CMake variables. See https://github.com/strukturag/libheif/blob/master/CMakeLists.txt#L103-L114 for an approach that works for both Autotools and CMake, is relocatable, and supports NixOS absolute paths. @pkrause1980

**Comment by kmilos** [comment]
Please see also https://github.com/msys2/MINGW-packages/pull/15365/files#diff-3fdae71ac2fc6fc7cfca1eb5b4db49ced58ad93982d699c6fd804c6987e43b3b for other suggested .pc.in template changes.

**Comment by farindk** [comment]
I have reverted 388b614 and copied over the same approach as used in libheif to fill-in the variables from CMake. Works again for me. Could you please check whether it also works for you?

**Comment by kmilos** [comment]
@farindk Can you please include the extra 2 lines from the MSYS2 patch please? There's no reason to substitute those.
